source 'https://rubygems.org/' 

gem "sinatra"
gem "koala"
gem "json", "1.5.5"
gem "httparty"
gem "thin"
gem "rack", "1.3.10"
gem "sqlite3"
gem "dm-core"
gem "dm-sqlite-adapter"
gem "dm-migrations"
gem "dm-validations"
gem "dm-timestamps"
